routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::name('admin.')->prefix('admin_panel')->group(function () {
    Route::get('/', 'Admin\IndexController@index')->name('home');
    Route::resource('companies', 'Admin\Catalog\CompaniesController');
    Route::resource('employers', 'Admin\Catalog\EmployersController');
});

app/Http/Controllers/Admin/Catalog/CompaniesController.php
<?php

namespace App\Http\Controllers\Admin\Catalog;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\StoreCompanies;
use App\Http\Helpers\Image;

use App\Companies;

class CompaniesController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $companies = Companies::getCompanies();

        return view('admin.catalog.companies.index', compact('companies'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.catalog.companies.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreCompanies $request)
    {
        $validated = $request->validated();

        $images = $_FILES;
        $image = Image::saveImage($images['logo'], config('app.image_upload_dir'));

        Companies::saveCompany($request, $image);

        return redirect('/admin_panel/companies')->with('success', 'Companies has been added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $company = Companies::getCompany($id);

        return view('admin.catalog.companies.edit', compact('company'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreCompanies $request, $id)
    {
        $validated = $request->validated();

        $images = $_FILES;
        $image = Image::updateImage($images['logo'], $request->get('old_image'), config('app.image_upload_dir'));

        Companies::updateCompany($request, $id, $image);

        return redirect('/admin_panel/companies')->with('success', 'Companies has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Companies::removeCompany($id);

        return redirect('/admin_panel/companies')->with('success', 'Companies has been removed');
    }
}

app/Http/Controllers/Admin/Catalog/EmployersController.php
<?php

namespace App\Http\Controllers\Admin\Catalog;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\StoreEmployers;

use App\Employers;
use App\Companies;

class EmployersController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $employers = Employers::getEmployers();

        return view('admin.catalog.employers.index', compact('employers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $companies = Companies::getCompanies();

        return view('admin.catalog.employers.create', compact('companies'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreEmployers $request)
    {
        $validated = $request->validated();

        Employers::saveEmployer($request);

        return redirect('/admin_panel/employers')->with('success', 'Employers has been added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $companies = Companies::getCompanies();
        $employer = Employers::getEmployer($id);

        return view('admin.catalog.employers.edit', compact('employer', 'companies'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreEmployers $request, $id)
    {
        $validated = $request->validated();

        Employers::updateEmployer($request, $id);

        return redirect('/admin_panel/employers')->with('success', 'Employers has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Employers::removeEmployer($id);

        return redirect('/admin_panel/employers')->with('success', 'Employers has been removed');
    }
}

resources/views/admin/catalog/companies/create.blade.php
@extends('admin.layouts.admin')

@section('content')
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
        <h1 class="m-0 text-dark">Create Company</h1>
        
        @if(session()->get('errors'))
            <div class="alert alert-danger">
            {{ session()->get('errors') }}  
            </div><br />
        @endif
        </div><!-- /.col -->
    </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <div class="row">

            <div class="col-sm-12">
                <div class="card card-primary">
                <!-- form start -->
                <form role="form" enctype="multipart/form-data" method="post" action="{{ route('admin.companies.store') }}">
                    @csrf
                    <div class="card-body">
                        <div class="form-group">
                            <label for="name">Name</label>
                            <input type="text" name="name" class="form-control" placeholder="Enter name" value="{{ old('name') }}">
                        </div>
                        <div class="form-group">
                            <label for="email">Email address</label>
                            <input type="email" name="email" class="form-control" placeholder="Enter email" value="{{ old('email') }}">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputFile">Logo</label>
                            <div class="input-group">
                            <div class="custom-file">
                                <input type="file" name="logo" class="custom-file-input" id="logo" value="{{ old('logo') }}">
                                <label class="custom-file-label" for="logo">Choose file</label>
                            </div>
                            <div class="input-group-append">
                                <span class="input-group-text" id="">Upload</span>
                            </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="website">Website</label>
                            <input type="text" name="website" class="form-control" placeholder="Enter website" value="{{ old('website') }}">
                        </div>
                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- /.main-content -->
        
@endsection

resources/views/admin/catalog/companies/edit.blade.php
@extends('admin.layouts.admin')

@section('content')
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
        <h1 class="m-0 text-dark">Edit Company</h1>
        
        @if(session()->get('errors'))
            <div class="alert alert-danger">
            {{ session()->get('errors') }}  
            </div><br />
        @endif
        </div><!-- /.col -->
    </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <div class="row">

            <div class="col-sm-12">
                <div class="card card-primary">
                <!-- form start -->
                <form role="form" enctype="multipart/form-data" method="post" action="{{ route('admin.companies.update', $company->id) }}">
                    @method('PATCH')
                    @csrf
                    <div class="card-body">
                        <div class="form-group">
                            <label for="name">Name</label>
                            <input type="text" name="name" class="form-control" placeholder="Enter name" value="{{ old('name') ?? $company->name }}">
                        </div>
                        <div class="form-group">
                            <label for="email">Email address</label>
                            <input type="email" name="email" class="form-control" placeholder="Enter email" value="{{ old('email') ?? $company->email }}">
                        </div>
                        <div class="form-group">
                            <label for="exampleInputFile">Logo</label>
                            <img src="{{ Storage::url($company->logo) }}"/>
                            <div class="input-group">
                            <div class="custom-file">
                                <input type="file" name="logo" class="custom-file-input" id="logo" value="{{ old('logo') ?? $company->logo }}">
                                <label class="custom-file-label" for="logo">Choose file</label>
                            </div>
                            <div class="input-group-append">
                                <span class="input-group-text" id="">Upload</span>
                            </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="website">Website</label>
                            <input type="text" name="website" class="form-control" placeholder="Enter website" value="{{ old('website') ?? $company->website }}">
                        </div>
                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- /.main-content -->
        
@endsection

resources/views/admin/catalog/companies/index.blade.php
@extends('admin.layouts.admin')

@section('content')
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
        <h1 class="m-0 text-dark">Companies</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
            <a href="{{ route('admin.companies.create')}}" class="btn btn-success float-right">Add</a>
        </div>
    </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <div class="row">

            <div class="col-sm-12">
                <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                    <thead>
                    <tr role="row">
                        <th tabindex="0" rowspan="1" colspan="1">Id</th>
                        <th tabindex="0" rowspan="1" colspan="1">Name</th>
                        <th tabindex="0" rowspan="1" colspan="1">Email</th>
                        <th tabindex="0" rowspan="1" colspan="1">Logo</th>
                        <th tabindex="0" rowspan="1" colspan="1">Website</th>
                        <th tabindex="0" rowspan="1" colspan="2">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                        @foreach($companies as $company)
                        <tr role="row" class="odd">
                            <td>{{$company->id}}</td>
                            <td>{{$company->name}}</td>
                            <td>{{$company->email}}</td>
                            <td>{{$company->logo}}</td>
                            <td>{{$company->website}}</td>
                            <td><a href="{{ route('admin.companies.edit',$company->id)}}" class="btn btn-primary">Edit</a></td>
                            <td>
                                <form action="{{ route('admin.companies.destroy', $company->id)}}" method="post">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger" type="submit">Delete</button>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                    <tfoot>
                        <tr>
                            <th rowspan="1" colspan="1">Id</th>
                            <th rowspan="1" colspan="1">Name</th>
                            <th rowspan="1" colspan="1">Email</th>
                            <th rowspan="1" colspan="1">Logo</th>
                            <th rowspan="1" colspan="1">Website</th>
                            <th rowspan="1" colspan="2">Action</th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>

        {{ $companies->links() }}
    </div>
</section>
<!-- /.main-content -->
        
@endsection