routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::name('admin.')->prefix('admin_panel')->group(function () {
    Route::get('/', 'Admin\IndexController@index')->name('home');
    Route::resource('companies', 'Admin\Catalog\CompaniesController');
    Route::resource('employers', 'Admin\Catalog\EmployersController');
});

app/Employers.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employers extends Model
{
    protected $fillable = [
        'firstname', 'lastname', 'email', 'phone', 'company_id'
    ];

    public function company() {
        return $this->belongsTo('App\Companies');
    }
    
    public static function getEmployers(){
    	return Employers::paginate(2);
    }

    public static function getEmployer($id){
    	return Employers::find($id);
    }

    public static function saveEmployer($request){
        $employer = new Employers([
            'firstname'     => $request->get('firstname'),
            'lastname'      => $request->get('lastname'),
            'email'         => $request->get('email'),
            'phone'         => $request->get('phone'),
            'company_id'    => $request->get('company_id'),
        ]);
        $employer->save();
    }

    public static function updateEmployer($request, $id){
        $employer = Employers::find($id);
        $employer->firstname    = $request->get('firstname');
        $employer->lastname     = $request->get('lastname');
        $employer->email        = $request->get('email');
        $employer->phone        = $request->get('phone');
        $employer->company_id   = $request->get('company_id');
        $employer->save();
    }

    public static function removeEmployer($id){
        Employers::destroy($id);
    }
}

app/Http/Controllers/Admin/Catalog/CompaniesController.php
<?php

namespace App\Http\Controllers\Admin\Catalog;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\StoreCompanies;
use App\Http\Helpers\Image;

use App\Companies;

class CompaniesController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $companies = Companies::getCompanies();

        return view('admin.catalog.companies.index', compact('companies'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.catalog.companies.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreCompanies $request)
    {
        $validated = $request->validated();

        $images = $_FILES;
        $image = Image::saveImage($images['logo'], config('app.image_upload_dir'));

        Companies::saveCompany($request, $image);

        return redirect('/admin_panel/companies')->with('success', 'Companies has been added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $company = Companies::getCompany($id);

        return view('admin.catalog.companies.edit', compact('company'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreCompanies $request, $id)
    {
        $validated = $request->validated();

        $images = $_FILES;
        $image = Image::updateImage($images['logo'], $request->get('old_image'), config('app.image_upload_dir'));

        Companies::updateCompany($request, $id, $image);

        return redirect('/admin_panel/companies')->with('success', 'Companies has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Companies::removeCompany($id);

        return redirect('/admin_panel/companies')->with('success', 'Companies has been removed');
    }
}

app/Http/Controllers/Admin/Catalog/EmployersController.php
<?php

namespace App\Http\Controllers\Admin\Catalog;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\StoreEmployers;

use App\Employers;
use App\Companies;

class EmployersController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $employers = Employers::getEmployers();

        return view('admin.catalog.employers.index', compact('employers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $companies = Companies::getCompanies();

        return view('admin.catalog.employers.create', compact('companies'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreEmployers $request)
    {
        $validated = $request->validated();

        Employers::saveEmployer($request);

        return redirect('/admin_panel/employers')->with('success', 'Employers has been added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $companies = Companies::getCompanies();
        $employer = Employers::getEmployer($id);

        return view('admin.catalog.employers.edit', compact('employer', 'companies'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreEmployers $request, $id)
    {
        $validated = $request->validated();

        Employers::updateEmployer($request, $id);

        return redirect('/admin_panel/employers')->with('success', 'Employers has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Employers::removeEmployer($id);

        return redirect('/admin_panel/employers')->with('success', 'Employers has been removed');
    }
}

resources/views/admin/catalog/employers/create.blade.php
@extends('admin.layouts.admin')

@section('content')
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
        <h1 class="m-0 text-dark">Create Employer</h1>
        
        @if(session()->get('errors'))
            <div class="alert alert-danger">
            {{ session()->get('errors') }}  
            </div><br />
        @endif
        </div><!-- /.col -->
    </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <div class="row">

            <div class="col-sm-12">
                <div class="card card-primary">
                <!-- form start -->
                <form role="form" enctype="multipart/form-data" method="post" action="{{ route('admin.employers.store') }}">
                    @csrf
                    <div class="card-body">
                    <div class="form-group">
                            <label for="name">First Name</label>
                            <input type="text" name="firstname" class="form-control" placeholder="Enter firstname" value="{{ old('firstname') }}">
                        </div>
                        <div class="form-group">
                            <label for="name">Last Name</label>
                            <input type="text" name="lastname" class="form-control" placeholder="Enter lastname" value="{{ old('lastname') }}">
                        </div>
                        <div class="form-group">
                            <label for="email">Email address</label>
                            <input type="email" name="email" class="form-control" placeholder="Enter email" value="{{ old('email') }}">
                        </div>
                        <div class="form-group">
                            <label for="name">Phone</label>
                            <input type="text" name="phone" class="form-control" placeholder="Enter phone" value="{{ old('phone') }}">
                        </div>
                        <div class="form-group">
                            <label>Select</label>
                            <select name="company_id" class="form-control">
                            @foreach($companies as $company)
                            <option value="{{$company->id}}">{{$company->name}}</option>
                            @endforeach
                            </select>
                        </div>
                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- /.main-content -->
        
@endsection

resources/views/admin/catalog/employers/edit.blade.php
@extends('admin.layouts.admin')

@section('content')
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
        <h1 class="m-0 text-dark">Edit Company</h1>
        
        @if(session()->get('errors'))
            <div class="alert alert-danger">
            {{ session()->get('errors') }}  
            </div><br />
        @endif
        </div><!-- /.col -->
    </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <div class="row">

            <div class="col-sm-12">
                <div class="card card-primary">
                <!-- form start -->
                <form role="form" enctype="multipart/form-data" method="post" action="{{ route('admin.employers.update', $employer->id) }}">
                    @method('PATCH')
                    @csrf
                    <div class="card-body">
                        <div class="form-group">
                            <label for="name">First Name</label>
                            <input type="text" name="firstname" class="form-control" placeholder="Enter firstname" value="{{ old('firstname') ?? $employer->firstname }}">
                        </div>
                        <div class="form-group">
                            <label for="name">Last Name</label>
                            <input type="text" name="lastname" class="form-control" placeholder="Enter lastname" value="{{ old('lastname') ?? $employer->lastname }}">
                        </div>
                        <div class="form-group">
                            <label for="email">Email address</label>
                            <input type="email" name="email" class="form-control" placeholder="Enter email" value="{{ old('email') ?? $employer->email }}">
                        </div>
                        <div class="form-group">
                            <label for="name">Phone</label>
                            <input type="text" name="phone" class="form-control" placeholder="Enter phone" value="{{ old('phone') ?? $employer->phone }}">
                        </div>
                        <div class="form-group">
                            <label>Select</label>
                            <select name="company_id" class="form-control">
                            @foreach($companies as $company)
                            @if($company->id == $employer->company_id)
                            <option selected value="{{$company->id}}">{{$company->name}}</option>
                            @else
                            <option value="{{$company->id}}">{{$company->name}}</option>
                            @endif
                            @endforeach
                            </select>
                        </div>
                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- /.main-content -->
        
@endsection

resources/views/admin/catalog/employers/index.blade.php
@extends('admin.layouts.admin')

@section('content')
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
        <h1 class="m-0 text-dark">Companies</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
            <a href="{{ route('admin.employers.create')}}" class="btn btn-success float-right">Add</a>
        </div>
    </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <div class="row">

            <div class="col-sm-12">
                <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                    <thead>
                    <tr role="row">
                        <th tabindex="0" rowspan="1" colspan="1">Id</th>
                        <th tabindex="0" rowspan="1" colspan="1">First Name</th>
                        <th tabindex="0" rowspan="1" colspan="1">Last Name</th>
                        <th tabindex="0" rowspan="1" colspan="1">Email</th>
                        <th tabindex="0" rowspan="1" colspan="1">Phone</th>
                        <th tabindex="0" rowspan="1" colspan="1">Company</th>
                        <th tabindex="0" rowspan="1" colspan="2">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                        @foreach($employers as $employer)
                        <tr role="row" class="odd">
                            <td>{{$employer->id}}</td>
                            <td>{{$employer->firstname}}</td>
                            <td>{{$employer->lastname}}</td>
                            <td>{{$employer->email}}</td>
                            <td>{{$employer->phone}}</td>
                            <td>{{$employer->company()->first()->name}}</td>
                            <td><a href="{{ route('admin.employers.edit',$employer->id)}}" class="btn btn-primary">Edit</a></td>
                            <td>
                                <form action="{{ route('admin.employers.destroy', $employer->id)}}" method="post">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger" type="submit">Delete</button>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                    <tfoot>
                        <tr>
                            <th rowspan="1" colspan="1">Id</th>
                            <th rowspan="1" colspan="1">First Name</th>
                            <th rowspan="1" colspan="1">Last Name</th>
                            <th rowspan="1" colspan="1">Email</th>
                            <th rowspan="1" colspan="1">Phone</th>
                            <th rowspan="1" colspan="1">Company</th>
                            <th rowspan="1" colspan="2">Action</th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>

        {{ $employers->links() }}
    </div>
</section>
<!-- /.main-content -->
        
@endsection